runtime: go
api_version: go1

handlers:
# All URLs are handled by the Go application script
- url: /.*
  script: _go_app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

